[build]
  command = "npm run build"
  publish = ".next"

# Omit build cache and other non-essential files from secrets scanning
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify,node_modules,.next/cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
